import { MainProvider } from "@/shared/provider/main-provider";
import { Nunito_Sans } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";



const nunitoSans = Nunito_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${nunitoSans.variable} antialiased`}>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
